### ISSUE TITLE
Error 429 temporary banned

### ISSUE THREAD

**Issue by nurps** [macherel/Barcode-Wallet#10]
Just wanted to install my new watch, by coping the token over. New watch is not getting the codes and shows Error 429.

When putting my token into the website it says "You have been temporary banned, please come back later."

I will come back later...

**Comment by flashpara** [comment]
I'm also getting this same error

**Comment by macherel** [comment]
I suppose you have using a non-valid (or expired) token (that's what the 403 error mean).
Also, to avoid brute-force testing, you can be banned temporarily if you have made to many attempt with an invalid token (the 429 error).
Please contact me by email using the "contact developer" link on the Garmin app store if you need some more help.
