### ISSUE TITLE
Space could be used better on large display F7X.

### ISSUE THREAD

**Issue by nurps** [macherel/Barcode-Wallet#17]
Simpler QR codes seem to be ok and are close the the screens border (still could be a little closer).

But my vaccination QR almost looks smaller then the one on my old F6, way to much unused space.
![20220531_125401](https://user-images.githubusercontent.com/6529125/171158236-2956a473-92af-45c8-b7ac-945fcd07aa3e.jpg)

**Comment by macherel** [comment]
duplicate of #9 

Just for you know, if your watch have a better resolution than an other, your code can looks smaller because each pixel is smaller (and using 2 pixels for each square will makes the QR code too large)
