### ISSUE TITLE
Error on Forrerunner 745 - "IQ exclamation mark"

### ISSUE THREAD

**Issue by strnaddavid** [macherel/Barcode-Wallet#18]
When I try to open the app on Forrerunner 745, I see only the icon "IQ exclamation mark"... See the printscreen: 

![barcode1](https://user-images.githubusercontent.com/56912898/172163287-50102168-6674-4761-9a8d-4f9254f578bc.jpg)

The setting is as follows at this printscreen:

 ![barcode](https://user-images.githubusercontent.com/56912898/172163078-772d0bc6-0ce5-4c35-bc31-1a1bdf4c0e7f.jpg)

**Comment by xfirebg** [comment]
Same here. Vivoactive 3

**Comment by davidchezmoa** [comment]
Same here. Instinct 2

**Comment by zhouqianhao** [comment]
Same here. Forerunner 935.

**Comment by MueD-EGW** [comment]
Same Herr with Fenix 6 Pro and new update

**Comment by Keti890517** [comment]
Same on venu 2

**Comment by vsliouniaev** [comment]
Started happening on 945LTE as well now.

**Comment by drfra** [comment]
Same issue here on Enduro

**Comment by Keti890517** [comment]
Started to work on Venu 2 - I saw two apps for this barcode app on IQ connect, so I removed them first and then tried each of them individually and now it works, so maybe there are 2 versions and only 1 works.

**Comment by zhouqianhao** [comment]
> you're right it's only the widget that doesn't work, the app works fine

On my forerunner 935, the app also dose not work.

**Comment by xfirebg** [comment]
Just re-installed the app after an update. Seems OK now.

**Comment by Iggy9730** [comment]
Getting the same error on my Fenix 6 Solar. Widget works; App does not.

**Comment by sanp** [comment]
Is the developer even reading these?

**Comment by xfirebg** [comment]
> Is the developer even reading these?

See my comment. I have now problems now...

**Comment by sanp** [comment]
> > Is the developer even reading these?
> 
> See my comment. I have no problems now...

I installed the latest version (1.8.8) on my venu 2 plus, and not only did it not work, it did not allow me to uninstall it. I had to force an uninstall by following the advice in [this thread](https://forums.garmin.com/sports-fitness/healthandwellness/f/venu-2/281004/can-t-delete-a-device-app/1470665#1470665) to even get it off of my watch. Other users report having the same issue with uninstalling this app too. Now that I've finally got it off my phone, I have no plans to try to get it back on.

**Comment by enbogdan** [comment]
Got the same error on F745 after I updated the widget and then the same after I installed the app.
Uninstalled both the widget and the app, installed the app, then for me it worked to display the codes.

**Comment by btpv** [comment]
same for my fenix 7x 
as soon as i change the settings

**Comment by LostEchoes** [comment]
Here are some working solutions I have found on the review pages of the Widget and the App

Solution 1:
Andrew Tempest
May 31, 2022 | Version 1.8.7
https://apps.garmin.com/en-US/apps/6840e507-b9fb-4d31-b990-2a711353ce00?tab=reviews&displayCurrentVersion=false

I updated my barcodes for the first time in months and found that configuring the widget settings in the Garmin Connect app on my phone will break the widget and IQ! will be displayed. This is the only way I could fix it: - open Garmin Express on the PC and plug-in the watch - open the IQ Apps page and remove the widget from the watch - unplug the watch and wait for startup (important) - plug-in the watch - download the widget from the Garmin Connect IQ store and let Garmin Express install it - open the widget settings on the IQ Apps page in Garmin Express - enter token, etc. - unplug and wait for startup - ensure watch is connected to the phone - open the widget on the watch - barcodes should appear v. shortly Changing the widget settings using Garmin Express seems reliable. Using the Garmin Connect app will break it again. Hope this helps. 

Solution 2:
Cornel Bugoi
October 2, 2022
https://apps.garmin.com/en-US/apps/ad2ef902-b229-4ab8-bd0e-86c102529f93

The IQ error, I was able to work around by reinstalling the app and set up the token right after installing it. I believe if you modify the settings of the app a second time, then you are stuck with that IQ error. Steps to perform: - uninstall the app - close the app IQConnect - reopen the app - install the wallet app and set the token right away - do not modify the settings anymore

**Comment by xaviersand** [comment]
i had this error on venu2. I uninstalled and re-installed the app and it worked.

**Comment by macherel** [comment]
There was a major issue since more than 1 year (but unfortunately was wasn't able to reproduce it on my watch).  
It seems that it was cause by an update of the Garmin firmware.
I discover a few weeks ago that my code didn't compile anymore with the latest SDK (due to additional checks that have been added by Garmin)
So I made a lot of changes to make it compile again. I hope this will solve this issue.
I updated the app a few days ago.
Please let me know it you still have some problem or not.
