### ISSUE TITLE
Temporary Tokens

### ISSUE THREAD

**Issue by stephankistner** [macherel/Barcode-Wallet#21]
My current token has expired and creating a new one only allows for a temporary token which will expire in 7 days.
Any way around this?

**Comment by macherel** [comment]
Yes, I can remove the expiration date to anyone who help for this app (or give a tip).
This allow everyone to test the app and create as many token as they want.
In the other hand, I can easily remove these temporary tokens after few weeks.

You also have to know that token are used only to synchronize your codes with your watch. That means that you need a valid one only if you want to make changes. If your watch is synchronized, your codes will stay on it even if the token expires.
