### ISSUE TITLE
Error - 403 / when enabling Debug (for a deleted barcode that still shows up)

### ISSUE THREAD

**Issue by LostEchoes** [macherel/Barcode-Wallet#28]
Hi there.
So, I recently got a new Garmin Fenix 6 (I previously had a Fenix 6s) and when I installed the widget it worked fine.
I did notice, however, that there is a barcode I wanted to remove. So I went to https://data-manager.qrcode.macherel.fr/
and I deleted that record. The problem is that while that record does not exist anymore on that URL (with my valid token), the said barcode still exists on my watch. 
I enabled "debug" on the widget settings (via Connect IQ) thinking that a force sync would be initiated, but then what I'm getting is an error -403 when I launch the widget and after I press the "down" button I can see the barcodes without any further issue, but the deleted barcode is still there.

So, without the "debug" option enabled, I'm getting a fully functional widget but with the deleted barcode showing up.
With the "debug" option enabled, I'm getting initially an error-403 and then by pressing the down button I can see all the barcodes along with the supposedly deleted one.

Any ideas what's happening here, besides the obvious conclusion that the sync does not work correctly?

Thanks in advance.

Fenix 6 Silver / FW: 25.10

**Comment by macherel** [comment]
The app always try to synchronize the codes. But it is done silently if the debug mode is disabled.
When the debug mode is enabled, you can see the error during the synchronization.

The -403 error means that you have a bluetooth error (details here : https://developer.garmin.com/connect-iq/api-docs/Toybox/Communications.html).
Please check if your watch is properly connected to your phone and if the data connection of your phone is working.

**Comment by LostEchoes** [comment]
> The app always try to synchronize the codes. But it is done silently if the debug mode is disabled. When the debug mode is enabled, you can see the error during the synchronization.
> 
> The -403 error means that you have a bluetooth error (details here : https://developer.garmin.com/connect-iq/api-docs/Toybox/Communications.html). Please check if your watch is properly connected to your phone and if the data connection of your phone is working.

Thank you for your feedback.
My watch is properly connected to the phone and I've had no bluetooth issues. I mean it syncs with Garmin Connect and with Connect IQ with no issues. If there was an issue with bluetooth or my phone's data connection, then that issue would also affect the sync with GC and CIQ, the changes I make with the watchfaces,, etc, right? 
Of course the data connection of my phone is also working without any issues. 
So, the only issue I'm having is with this widget. That barcode (removed on the URL list)) is not removed from the list of the barcodes on the watch. I also tried adding  a new barcode and that also does not show up on the watch.

**Comment by macherel** [comment]
As it is a synchronization issue, if it fails to remove a code, it will also fail to add some.
Unfortunately, when users are facing such issue, I can't do anything exception asking them to try some workaround like rebooting the watch (and the phone). Personally, I periodically loose connection between my phone my watch and I suspect some bugs in Garmin Connect.

It's good to know that you solve your problem but it's weird you had to re-install the app to make it work. I really don't understand what happened.
