### ISSUE TITLE
Data manage ui report that my token expires. 

### ISSUE THREAD

**Issue by przemeklagod** [macherel/Barcode-Wallet#29]
What can I do ? 
![obraz](https://github.com/macherel/Barcode-Wallet/assets/97026701/ab0cf1d8-25b7-4e2f-a6f5-af2510c57161)

**Comment by macherel** [comment]
I can remove the expiration date to anyone who support the app (helping developing features, translating the app, giving a tip, ...).
You can also recreate a new token and reconfigure your codes if you have some change to do but don't want to support the app.
For the tip, you can use [paypal](http://paypal.me/macherel) or [buymeacofee](https://www.buymeacoffee.com/macherel).
If you just have some questions, the easiest way is to contact me using the Garmin app store (using the "contact developer" link) and let your email.
