### ISSUE TITLE
Forerunner 735XT QR Code Very Small

### ISSUE THREAD

**Issue by vsliouniaev** [macherel/Barcode-Wallet#7]
When using the app for a digital COVID cert. On the 735XT the code only takes up a fraction of the screen and is much too small to be scanned by a camera.

<img width="343" alt="Screenshot 2021-12-02 at 10 28 37" src="https://user-images.githubusercontent.com/1751776/144404695-9a1aa14a-ea88-462f-bdca-3c7e600fc762.png">

**Comment by vsliouniaev** [comment]
My mistake - using the ^ button the size of the code can be increased

**Comment by wschoot** [comment]
Hm, this doesn't work for me on my fenix6x
